### ISSUE TITLE
Updation of UI with new HTML/CSS and JS

### ISSUE THREAD

**Issue by rai-gaurav** [preaction/Alien-SwaggerUI#2]
Is there any plan to upgrade the 'share' dir with the new Swagger UI ?

**Comment by preaction** [comment]
My use for this project is largely CPAN Testers (http://api.cpantesters.org/docs/?url=/v3). There have since been some better OpenAPI documentation projects (https://github.com/Redocly/redoc or the list here https://openapi.tools/#documentation) so I haven't been keeping up. I would certainly accept a pull request updating the version of Swagger in this distribution 😃

**Comment by rai-gaurav** [comment]
ok. I will try to do that. Thanks

**Comment by rai-gaurav** [comment]
Pull request: #3

**Comment by preaction** [comment]
Merged. Thanks for the help!
